# Generated by Django 3.1.2 on 2020-11-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='posty',
        ),
    ]
