# Generated by Django 3.1.2 on 2020-11-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_posty_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posty',
            name='like',
        ),
    ]
