# Generated by Django 3.1.2 on 2020-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_posty_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='posty',
            name='like',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
